---
- name: Get stats and write to home folder
  hosts: testservers
  tasks:
    - name: get system status and info
      shell: uname -a > /home/ubuntu/output.txt
    - name: print my username
      shell: whoami >> /home/ubuntu/output.txt
      